apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}-service-redis
spec:
  type: ClusterIP
  ports:
    - targetPort: 16379
      port: 16379
  selector:
    app: ${APPLICATION_NAME}-redis
